"""Run Elo tournaments to compare rationales from different evaluation models.

This module implements a pairwise tournament system using Elo ratings and other
algorithms to compare rationales generated by different models.
"""

from paper.gpt.evaluate_tournament import cli as cli
