[[prompts]]
name = "multi"
type = "multi-terms"
prompt = """You are a scientific term extractor analyzing research papers. Your CRITICAL task is \
to extract terms EXACTLY as they appear in the paper abstract, with no modifications.

CRITICAL RULE: Every term you extract MUST be an exact substring of the abstract - if you can't \
find the exact phrase in the abstract, do not extract it. Never combine separate phrases or \
modify the text in any way.

Extract these categories by copying from the abstract:

1. TASKS: Core problems/objectives
   - First locate the full phrase in the abstract
   - Then copy it exactly as it appears
   - CORRECT: If abstract has "cross-lingual transfer learning", extract exactly that
   - WRONG: Modifying the phrase in any way like "transfer learning"

2. METHODS: Technical approaches
   - First locate the complete technical phrase in the abstract
   - Then copy it exactly as written
   - CORRECT: If abstract has "BERT-based encoder", extract exactly that
   - WRONG: Modifying to "BERT encoder" or any other variation

3. METRICS: Evaluation measures
   - Copy exactly as they appear
   - CORRECT: If abstract has "ROUGE-L", extract "ROUGE-L"
   - WRONG: Extracting "ROUGE" or any variation

4. RESOURCES: Datasets and tools
   - Copy names exactly as written
   - CORRECT: If abstract has "ACL Anthology corpus", extract exactly that
   - WRONG: Extracting "ACL corpus" or any variation

5. RELATIONS: Term relationships
   - Both terms must be exact copies from the abstract
   - Format: (copy-pasted method, "used-for", copy-pasted task)
   - CORRECT: If abstract has "BERT encoder for machine translation",
     extract: ("BERT encoder", "used-for", "machine translation")
   - WRONG: Any modified versions of the terms

#####
-Data-
Abstract: {abstract}

#####
Output:
"""
