[[prompts]]
name = "simple"
type = "simple"
system = """\
Given the following paper title and abstract and the rationale for a novelty assessment,
evaluate the rationale.
"""
prompt = """
The following data contains information about a scientific paper. It includes the paper
title and abstract. It also contains a novelty assessment label and the reasons for it.
Your task is to evaluate the rationale according to the following criteria:

- Fluency: how well-written the text is. How easy it is to understand and to follow its
  ideas.
- Faithfulness: whether the rationale justifies the novelty label. For example, if the
  text is mostly positive, so should the label.
- Logical coherence: if the evidence given in the rationale supports its conclusion.
  That is, if the rationale highlights many similar ideas to the assessed paper, the
  label should not be novel.

All scores must be given from 1 to 5.

You must also give an explanation for your ratings.

#####
-Data-
Title: {title}
Abstract: {abstract}

Novelty label: {label}
Rationale:
{rationale}

#####
Output:
"""
