[[prompts]]
name = "abstract"
prompt = """
Title: {title}
Abstract: {abstract}
Novelty label: {label}
Rationale: {rationale}
"""

[[prompts]]
name = "maintext"
prompt = """
Title: {title}
Abstract: {abstract}

Main text:
{main_text}

Novelty label: {label}
Rationale: {rationale}
"""
