[[prompts]]
name = "abstract"
type = "n/a"
prompt = """
Title: {title}
Abstract: {abstract}
Decision: {decision}
Rationale: {rationale}
"""

[[prompts]]
name = "maintext"
type = "n/a"
prompt = """
Title: {title}
Abstract: {abstract}

Main text:
{main_text}

Decision: {decision}
Rationale: {rationale}
"""
