[[prompts]]
name = "abstract"
type = "n/a"
prompt = """
Title: {title}
Abstract: {abstract}
Novelty rating: {rating}
Rationale: {rationale}
"""

[[prompts]]
name = "maintext"
type = "n/a"
prompt = """
Title: {title}
Abstract: {abstract}

Main text:
{main_text}

Novelty rating: {rating}
Rationale: {rationale}
"""
