[[prompts]]
name = "full-graph"
system = """\
Given the following target paper, a summary and a selection of related papers separated \
by whether they're supporting or contrasting the main paper, give it a novelty rating.
"""
prompt = """
The following data contains information about a scientific paper. It includes the \
main paper's title, a summary of its key points and some related papers.

The paper summary describes the most important information about the paper and its \
contents. It summarises key aspects, which you can use to build a more comprehensive \
understanding of the paper.

The related papers are split into "supporting" papers (those that corroborate the paper's \
ideas, methods, approach, etc.) and "contrasting" papers (those that go against the \
paper's ideas). Use these related papers to understand the context around the main paper, \
so you know what other works exist in comparison with the main paper.

Based on this, decide whether the paper is novel. It is novel if brings new ideas or \
develops new ideas previously unseen. Make sure that the ideas are truly unique. The \
paper is not novel if anything similar to it has been done before. Be very thorough. \
When in doubt, tend towards the not novel label.

First, generate the rationale for your novelty label, then give the final novelty label. \
It should be 1 for a novel paper, or 0 otherwise. If you're uncertain, assign the 0 \
(not novel) label.

If the paper approval decision is "True", the novelty label should be 1 (novel).

#####
{demonstrations}

-Data-
Title: {title}
Abstract: {abstract}
Approval decision: {approval}

Paper summary:
{graph}

Supporting papers:
{positive}

Contrasting papers:
{negative}

#####
Output:
"""

[[prompts]]
name = "only-graph"
system = """\
Given the following target paper, a summary and a selection of related papers separated \
by whether they're supporting or contrasting the main paper, give it a novelty rating.
"""
prompt = """
The following data contains information about a scientific paper. It includes the \
main paper's title, a summary of its key points and some related papers.

The paper summary describes the most important information about the paper and its \
contents. It summarises key aspects, which you can use to build a more comprehensive \
understanding of the paper.

The related papers are split into "supporting" papers (those that corroborate the paper's \
ideas, methods, approach, etc.) and "contrasting" papers (those that go against the \
paper's ideas). Use these related papers to understand the context around the main paper, \
so you know what other works exist in comparison with the main paper.

Based on this content, decide whether the paper is novel enough or not. If it is, give \
it a label of 1. If it isn't, give it a label of 0. This should reflect how much the \
paper brings and develops new ideas previously unseen in the literature. First, generate \
the rationale for your novelty rating, then give the final novelty rating.

If the paper approval decision is "True", the novelty label should be 1 (novel).

#####
{demonstrations}

-Data-
Approval decision: {approval}

Paper summary:
{graph}

Supporting papers:
{positive}

Contrasting papers:
{negative}

#####
Output:
"""

[[prompts]]
name = "title-graph"
system = """\
Given the following target paper, a summary and a selection of related papers separated \
by whether they're supporting or contrasting the main paper, give it a novelty rating.
"""
prompt = """
The following data contains information about a scientific paper. It includes the \
main paper's title, a summary of its key points and some related papers.

The paper summary describes the most important information about the paper and its \
contents. It summarises key aspects, which you can use to build a more comprehensive \
understanding of the paper.

The related papers are split into "supporting" papers (those that corroborate the paper's \
ideas, methods, approach, etc.) and "contrasting" papers (those that go against the \
paper's ideas). Use these related papers to understand the context around the main paper, \
so you know what other works exist in comparison with the main paper.

Based on this content, decide whether the paper is novel enough or not. If it is, give \
it a label of 1. If it isn't, give it a label of 0. This should reflect how much the \
paper brings and develops new ideas previously unseen in the literature. First, generate \
the rationale for your novelty rating, then give the final novelty rating.

If the paper approval decision is "True", the novelty label should be 1 (novel).

#####
{demonstrations}

-Data-
Title: {title}
Approval decision: {approval}

Paper summary:
{graph}

Supporting papers:
{positive}

Contrasting papers:
{negative}

#####
Output:
"""

[[prompts]]
name = "related"
system = """\
Given the following target paper and a selection of related papers separated by whether \
they're supporting or contrasting the main paper, give a novelty rating to a paper \
submitted to a high-quality scientific conference.
"""
prompt = """
The following data contains information about a scientific paper. It includes the \
main paper's title and abstract and some related papers. These related papers are \
separated by "supporting" papers (those that corroborate the paper's ideas, methods,
approach, etc.) and "contrasting" papers (those that go against the paper's ideas).

Based on this content, decide whether the paper is novel enough or not. If it is, give \
it a label of 1. If it isn't, give it a label of 0. This should reflect how much the \
paper brings and develops new ideas previously unseen in the literature. First, generate \
the rationale for your novelty rating, then give the final novelty rating.

If the paper approval decision is "True", the novelty label should be 1 (novel).

#####
{demonstrations}

-Data-
Title: {title}
Abstract: {abstract}
Approval decision: {approval}

Supporting papers:
{positive}

Contrasting papers:
{negative}

#####
Output:
"""

[[prompts]]
name = "sans"
system = """\
Give an approval or rejection to a paper submitted to a high-quality scientific \
conference.\
"""
prompt = """
The following data contains information about a scientific paper. It includes the \
paper's title and abstract.

Based on this content, decide whether the paper is novel enough or not. If it is, give \
it a label of 1. If it isn't, give it a label of 0. This should reflect how much the \
paper brings and develops new ideas previously unseen in the literature. First, generate \
the rationale for your novelty rating, then give the final novelty rating.

If the paper approval decision is "True", the novelty label should be 1 (novel).

#####
{demonstrations}

-Data-
Title: {title}
Abstract: {abstract}
Approval decision: {approval}

#####
Output:
"""

[[prompts]]
name = "norel-graph"
system = """\
Given the following target paper and summary, give it a novelty rating.
"""
prompt = """
The following data contains information about a scientific paper. It includes the \
main paper's title and a summary of its key points.

The paper summary describes the most important information about the paper and its \
contents. It summarises key aspects, which you can use to build a more comprehensive \
understanding of the paper.

Based on this content, decide whether the paper is novel enough or not. If it is, give \
it a label of 1. If it isn't, give it a label of 0. This should reflect how much the \
paper brings and develops new ideas previously unseen in the literature. First, generate \
the rationale for your novelty rating, then give the final novelty rating.

If the paper approval decision is "True", the novelty label should be 1 (novel).

#####
{demonstrations}

-Data-
Title: {title}
Abstract: {abstract}
Approval decision: {approval}

Paper summary:
{graph}

#####
Output:
"""

# Full graph with only positive/supporting papers
[[prompts]]
name = "full-graph-positive"
system = """\
Given the following target paper, a summary and a selection of related papers supporting \
the main paper, give it a novelty rating.
"""
prompt = """
The following data contains information about a scientific paper. It includes the \
main paper's title, a summary of its key points and some related papers.

The paper summary describes the most important information about the paper and its \
contents. It summarises key aspects, which you can use to build a more comprehensive \
understanding of the paper.

The related papers support the main paper, i.e. they corroborate the paper's ideas, methods, \
approach, etc. Use these related papers to understand the context around the main paper, \
so you know what other works exist in comparison with the main paper.

Based on this content, decide whether the paper is novel enough or not. If it is, give \
it a label of 1. If it isn't, give it a label of 0. This should reflect how much the \
paper brings and develops new ideas previously unseen in the literature. First, generate \
the rationale for your novelty rating, then give the final novelty rating.

If the paper approval decision is "True", the novelty label should be 1 (novel).

#####
{demonstrations}

-Data-
Title: {title}
Abstract: {abstract}
Approval decision: {approval}

Paper summary:
{graph}

Supporting papers:
{positive}

#####
Output:
"""

# Full graph with only negative/contrasting papers
[[prompts]]
name = "full-graph-negative"
system = """\
Given the following target paper, a summary and a selection of related papers \
contrasting the main paper, give it a novelty rating.
"""
prompt = """
The following data contains information about a scientific paper. It includes the \
main paper's title, a summary of its key points and some related papers.

The paper summary describes the most important information about the paper and its \
contents. It summarises key aspects, which you can use to build a more comprehensive \
understanding of the paper.

The related papers contrast the main paper, i.e. they go against the main paper's \
ideas. Use these related papers to understand the context around the main paper, \
so you know what other works exist in comparison with the main paper.

Based on this content, decide whether the paper is novel enough or not. If it is, give \
it a label of 1. If it isn't, give it a label of 0. This should reflect how much the \
paper brings and develops new ideas previously unseen in the literature. First, generate \
the rationale for your novelty rating, then give the final novelty rating.

#####
{demonstrations}

-Data-
Title: {title}
Abstract: {abstract}
Approval decision: {approval}

Paper summary:
{graph}

Supporting papers:
{positive}

Contrasting papers:
{negative}

#####
Output:
"""

[[prompts]]
name = "attribution-graph"
system = """\
Given the following target paper, a summary and a selection of related papers separated \
by whether they're supporting or contrasting the main paper, give it a novelty rating.
"""
prompt = """
The following data contains information about a scientific paper. It includes the \
main paper's title, a summary of its key points and some related papers.

The paper summary describes the most important information about the paper and its \
contents. It summarises key aspects, which you can use to build a more comprehensive \
understanding of the paper.

The related papers are split into "supporting" papers (those that corroborate the paper's \
ideas, methods, approach, etc.) and "contrasting" papers (those that go against the \
paper's ideas). Use these related papers to understand the context around the main paper, \
so you know what other works exist in comparison with the main paper.

#####
{demonstrations}

-Data-
Title: {title}
Abstract: {abstract}
Approval decision: {approval}

Paper summary:
{graph}

Supporting papers:
{positive}

Contrasting papers:
{negative}
#####

Based on this, decide whether the paper is novel. It is novel if brings new ideas or \
develops new ideas previously unseen. Make sure that the ideas are truly unique. The \
paper is not novel if anything similar to it has been done before. Be very thorough. \
When in doubt, tend towards the not novel label.

First, generate the rationale for your novelty label, then give the final novelty label. \
It should be 1 for a novel paper, or 0 otherwise. If you're uncertain, assign the 0 \
(not novel) label.

For each related paper, assign a code to them. When discussing related papers in the \
rationale, be specific and use the paper's code. After the rationale, add a references \
section with the code and name for each paper. For brevity, don't use the paper names \
in the rationale, only the code. Make sure that all referenced papers appear in the \
references section.

If the paper approval decision is "True", the novelty label should be 1 (novel).
"""
