[[prompts]]
name = "simple"
type = "full"
prompt = """
The following data contains information about a scientific paper. It includes the \
paper's title, abstract, and the full body text.

Based on this content, approve or reject the paper. First, generate the rationale for \
your decision, then give the final decision. Keep in mind that this paper was submitted \
to a very high-quality conference, so make sure to only approve papers that are of \
outstanding quality.

#####
-Data-
Title: {title}
Abstract: {abstract}

Main text:
{main_text}

#####
Output:
"""
