[[prompts]]
name = "simple"
prompt = """
The following data contains information about a scientific paper. It includes the \
paper's title and abstract. Based on this, your task is to extract all atomic content \
units from the paper.

1. First, extract the list of all atomic content units (ACUs) from a given document. An \
ACU is an elementary information unit in the document that does not require further \
division. When identifying any named entity, temporal entity, location entity, or \
attribute, avoid using indirect references. Instead, specify the actual entity, \
attribute, or noun directly. For example, replace 'this company' with the actual name \
of the company, 'this location' with the actual location name, 'it' with the actual \
subject being referred, etc.

2. Then, summarize the given document.

3. Finally, using the summary, identify the most salient ACUs from the full list of \
ACUs. The salient ACUs should be those explicitly mentioned in the summary.

#####
-Demonstration-
Example document:

Enzon Inc. said tests of a new anti-cancer drug to treat a form of leukemia showed \
positive results, Abraham Abuchowski, president of the pharmeutical company, told the \
annual meeting. Enzon also said it filed its first new drug application with the FDA \
for an orphan drug that treats severe combined immunodeficiency disease, or SCID. The \
company has about 10.8 million common shares outstanding. Eastman Kodak Co. ownas an 18% \
interest in Enzon.

Example ACUs:
- Enzon Inc. reported positive results from tests of a new anti-cancer drug for leukemia.
- Abraham Abuchowski is the president of Enzon Inc.
- Enzon Inc. filed a new drug with the FDA to treat immunodeficiency disease.
- Enzon Inc. has about 10.8 million common shares outstanding.

-Data-
Title: {title}
Abstract: {abstract}

#####
Output:
"""

[[prompts]]
name = "detailed"
prompt = """
The following data contains information about a scientific paper. It includes the \
paper's title and abstract. Based on this, your task is to extract all atomic content \
units from the paper.

1. First, extract the list of all atomic content units (ACUs) from the scientific paper abstract. 
An ACU is an elementary information unit that captures a single, specific claim, finding, 
method, or concept from the paper. Each ACU should be:
   - Self-contained and complete (a full sentence that can stand on its own)
   - Specific and detailed (including precise methods, values, or findings when mentioned)
   - Factual (not interpretations or generalizations)
   - Comprehensive (cover all important aspects of the research in the abstract)

Be thorough and extract all possible ACUs from the abstract.

2. Then, summarize the given document.

3. Finally, using your summary, identify the most salient ACUs from the full list of \
ACUs. The salient ACUs should be those that capture the paper's core contributions.

#####
-Demonstration 1-
Example document:

Enzon Inc. said tests of a new anti-cancer drug to treat a form of leukemia showed \
positive results, Abraham Abuchowski, president of the pharmeutical company, told the \
annual meeting. Enzon also said it filed its first new drug application with the FDA \
for an orphan drug that treats severe combined immunodeficiency disease, or SCID. The \
company has about 10.8 million common shares outstanding. Eastman Kodak Co. ownas an 18% \
interest in Enzon.

Example ACUs:
- Enzon Inc. reported positive results from tests of a new anti-cancer drug for leukemia.
- Abraham Abuchowski is the president of Enzon Inc.
- Enzon Inc. filed a new drug application with the FDA to treat severe combined immunodeficiency disease (SCID).
- SCID is classified as an orphan disease.
- Enzon Inc. has about 10.8 million common shares outstanding.
- Eastman Kodak Co. owns an 18% interest in Enzon Inc.

-Demonstration 2-
Example document:

Deep neural networks can be obscenely wasteful. When processing video, a convolutional network expends a fixed amount of computation for each frame with no regard to the similarity between neighbouring frames. As a result, it ends up repeatedly doing very similar computations. To put an end to such waste, we introduce SigmaDelta networks. With each new input, each layer in this network sends a discretized form of its change in activation to the next layer. Thus the amount of computation that the network does scales with the amount of change in the input and layer activations, rather than the size of the network. We introduce an optimization method for converting any pre-trained deep network into an optimally efficient Sigma-Delta network, and show that our algorithm, if run on the appropriate hardware, could cut at least an order of magnitude from the computational cost of processing video data.

Example ACUs:
- Deep neural networks can be excessively wasteful in terms of computational resources.
- When processing video, convolutional networks expend a fixed amount of computation for each frame regardless of similarities between neighboring frames.
- Convolutional networks often perform redundant computations when processing similar frames.
- The authors introduce Sigma-Delta networks to reduce computational waste.
- In Sigma-Delta networks, each layer sends a discretized form of its activation changes to the next layer.
- Computation in Sigma-Delta networks scales with the amount of change in input and layer activations, not with network size.
- The authors developed an optimization method to convert pre-trained deep networks into optimally efficient Sigma-Delta networks.
- The proposed algorithm could reduce computational cost of video processing by at least an order of magnitude.
- The computational benefits require appropriate hardware implementation.
- The optimization method works with any pre-trained deep network.
- Sigma-Delta networks are named after the mathematical concept of measuring change.

-Data-
Title: {title}
Abstract: {abstract}

#####
Output:
"""