[[prompts]]
name = "simple"
prompt = """
The following data contains information about a scientific paper. It includes the \
paper's title and abstract. Based on this, your task is to extract all atomic content \
units from the paper.

1. First, extract the list of all atomic content units (ACUs) from a given document. An \
ACU is an elementary information unit in the document that does not require further \
division. When identifying any named entity, temporal entity, location entity, or \
attribute, avoid using indirect references. Instead, specify the actual entity, \
attribute, or noun directly. For example, replace 'this company' with the actual name \
of the company, 'this location' with the actual location name, 'it' with the actual \
subject being referred, etc.

2. Then, summarize the given document.

3. Finally, using the summary, identify the most salient ACUs from the full list of \
ACUs. The salient ACUs should be those explicitly mentioned in the summary.

#####
-Demonstration-
Example document:

Enzon Inc. said tests of a new anti-cancer drug to treat a form of leukemia showed \
positive results, Abraham Abuchowski, president of the pharmeutical company, told the \
annual meeting. Enzon also said it filed its first new drug application with the FDA \
for an orphan drug that treats severe combined immunodeficiency disease, or SCID. The \
company has about 10.8 million common shares outstanding. Eastman Kodak Co. ownas an 18% \
interest in Enzon.

Example ACUs:
- Enzon Inc. reported positive results from tests of a new anti-cancer drug for leukemia.
- Abraham Abuchowski is the president of Enzon Inc.
- Enzon Inc. filed a new drug with the FDA to treat immunodeficiency disease.
- Enzon Inc. has about 10.8 million common shares outstanding.

-Data-
Title: {title}
Abstract: {abstract}

#####
Output:
"""

[[prompts]]
name = "detailed"
prompt = """
The following data contains information about a scientific paper. It includes the \
paper's title and abstract. Based on this, your task is to extract all atomic content \
units from the paper.

1. First, extract the list of all atomic content units (ACUs) from the scientific paper abstract.
An ACU is an elementary information unit that captures a single, specific claim, finding,
method, or concept from the paper. Each ACU should be:
   - Self-contained and complete (a full sentence that can stand on its own)
   - Specific and detailed (including precise methods, values, or findings when mentioned)
   - Factual (not interpretations or generalizations)
   - Comprehensive (cover all important aspects of the research in the abstract)

Be thorough and extract all possible ACUs from the abstract.

2. Then, summarize the given document.

3. Finally, using your summary, identify the most salient ACUs from the full list of \
ACUs. The salient ACUs should be those that capture the paper's core contributions.

#####
-Demonstration 1-
Example document:

Enzon Inc. said tests of a new anti-cancer drug to treat a form of leukemia showed \
positive results, Abraham Abuchowski, president of the pharmeutical company, told the \
annual meeting. Enzon also said it filed its first new drug application with the FDA \
for an orphan drug that treats severe combined immunodeficiency disease, or SCID. The \
company has about 10.8 million common shares outstanding. Eastman Kodak Co. ownas an 18% \
interest in Enzon.

Example ACUs:
- Enzon Inc. reported positive results from tests of a new anti-cancer drug for leukemia.
- Abraham Abuchowski is the president of Enzon Inc.
- Enzon Inc. filed a new drug application with the FDA to treat severe combined immunodeficiency disease (SCID).
- SCID is classified as an orphan disease.
- Enzon Inc. has about 10.8 million common shares outstanding.
- Eastman Kodak Co. owns an 18% interest in Enzon Inc.

-Demonstration 2-
Example document:

Deep neural networks can be obscenely wasteful. When processing video, a convolutional network expends a fixed amount of computation for each frame with no regard to the similarity between neighbouring frames. As a result, it ends up repeatedly doing very similar computations. To put an end to such waste, we introduce SigmaDelta networks. With each new input, each layer in this network sends a discretized form of its change in activation to the next layer. Thus the amount of computation that the network does scales with the amount of change in the input and layer activations, rather than the size of the network. We introduce an optimization method for converting any pre-trained deep network into an optimally efficient Sigma-Delta network, and show that our algorithm, if run on the appropriate hardware, could cut at least an order of magnitude from the computational cost of processing video data.

Example ACUs:
- Deep neural networks can be excessively wasteful in terms of computational resources.
- When processing video, convolutional networks expend a fixed amount of computation for each frame regardless of similarities between neighboring frames.
- Convolutional networks often perform redundant computations when processing similar frames.
- The authors introduce Sigma-Delta networks to reduce computational waste.
- In Sigma-Delta networks, each layer sends a discretized form of its activation changes to the next layer.
- Computation in Sigma-Delta networks scales with the amount of change in input and layer activations, not with network size.
- The authors developed an optimization method to convert pre-trained deep networks into optimally efficient Sigma-Delta networks.
- The proposed algorithm could reduce computational cost of video processing by at least an order of magnitude.
- The computational benefits require appropriate hardware implementation.
- The optimization method works with any pre-trained deep network.
- Sigma-Delta networks are named after the mathematical concept of measuring change.

-Data-
Title: {title}
Abstract: {abstract}

#####
Output:
"""

[[prompts]]
name = "sci"
prompt = """
Extract atomic content units (ACUs) from this scientific paper. An ACU represents a single, indivisible fact or claim from the paper.

For scientific papers, good ACUs should:
1. Capture specific scientific findings, methodologies, or conclusions
2. Preserve precise technical details, measurements, and relationships
3. Maintain scientific accuracy without simplification
4. Use the same technical terminology as the original text
5. Include all relevant entities, values, and conditions for each claim
6. Be standalone statements that can be individually verified

When extracting ACUs:
- Replace pronouns with their specific referents
- Preserve numeric values and units exactly as stated
- Maintain relationships between variables, conditions, and outcomes
- Include methodology details when relevant to findings
- Separate compound statements into individual claims

#####
-Demonstration-
Example document 1:

Enzon Inc. said tests of a new anti-cancer drug to treat a form of leukemia showed positive results, Abraham Abuchowski, president of the pharmeutical company, told the annual meeting. Enzon also said it filed its first new drug application with the FDA for an orphan drug that treats severe combined immunodeficiency disease, or SCID. The company has about 10.8 million common shares outstanding. Eastman Kodak Co. ownas an 18% interest in Enzon.

Example ACUs:
- Enzon Inc. conducted tests of a new anti-cancer drug for treating a form of leukemia.
- Tests of Enzon Inc.'s new anti-cancer drug for leukemia showed positive results.
- Abraham Abuchowski is the president of Enzon Inc.
- Abraham Abuchowski reported the positive test results at the annual meeting.
- Enzon Inc. filed its first new drug application with the FDA.
- The new drug application filed by Enzon Inc. with the FDA is for an orphan drug.
- The orphan drug developed by Enzon Inc. treats severe combined immunodeficiency disease (SCID).
- Enzon Inc. has approximately 10.8 million common shares outstanding.
- Eastman Kodak Co. owns an 18% interest in Enzon Inc.

Example document 2:

In a randomized controlled trial, researchers investigated the effects of a novel SGLT2 inhibitor on HbA1c levels in patients with type 2 diabetes. 128 participants were administered either 100mg of the inhibitor or a placebo daily for 12 weeks. Results showed that the treatment group (n=64) experienced a mean reduction in HbA1c of 1.8% (95% CI: 1.5-2.1%), compared to 0.4% (95% CI: 0.2-0.6%) in the control group (p<0.001). Additionally, the treatment group showed significant improvements in fasting plasma glucose (-2.3 mmol/L vs -0.6 mmol/L, p<0.001) and body weight (-2.7 kg vs -0.5 kg, p<0.01). Seven patients (10.9%) in the treatment group reported mild gastrointestinal side effects, compared to three patients (4.7%) in the placebo group.

Example ACUs:
- Researchers conducted a randomized controlled trial to investigate the effects of a novel SGLT2 inhibitor on HbA1c levels.
- The study focused on patients with type 2 diabetes.
- The trial included 128 participants in total.
- 64 participants received 100mg of the SGLT2 inhibitor daily.
- 64 participants received a placebo daily.
- The treatment duration was 12 weeks.
- The treatment group experienced a mean reduction in HbA1c of 1.8%.
- The 95% confidence interval for HbA1c reduction in the treatment group was 1.5-2.1%.
- The control group experienced a mean reduction in HbA1c of 0.4%.
- The 95% confidence interval for HbA1c reduction in the control group was 0.2-0.6%.
- The difference in HbA1c reduction between groups was statistically significant (p<0.001).
- The treatment group showed a reduction in fasting plasma glucose of 2.3 mmol/L.
- The control group showed a reduction in fasting plasma glucose of 0.6 mmol/L.
- The difference in fasting plasma glucose reduction was statistically significant (p<0.001).
- The treatment group showed a reduction in body weight of 2.7 kg.
- The control group showed a reduction in body weight of 0.5 kg.
- The difference in body weight reduction was statistically significant (p<0.01).
- Seven patients (10.9%) in the treatment group reported mild gastrointestinal side effects.
- Three patients (4.7%) in the placebo group reported mild gastrointestinal side effects.

-Data-
Title: {title}
Abstract: {abstract}

#####
Output:
"""
