primary_areas = [
    "unsupervised, self-supervised, semi-supervised, and supervised representation learning",
    "transfer learning, meta learning, and lifelong learning",
    "reinforcement learning",
    "representation learning for computer vision, audio, language, and other modalities",
    "metric learning, kernel learning, and sparse coding",
    "probabilistic methods (Bayesian methods, variational inference, sampling, UQ, etc.)",
    "generative models",
    "causal reasoning",
    "optimization",
    "learning theory",
    "learning on graphs and other geometries & topologies",
    "societal considerations including fairness, safety, privacy",
    "visualization or interpretation of learned representations",
    "datasets and benchmarks",
    "infrastructure, software libraries, hardware, etc.",
    "neurosymbolic & hybrid AI systems (physics-informed, logic & formal reasoning, etc.)",
    "applications to robotics, autonomy, planning",
    "applications to neuroscience & cognitive science",
    "applications to physical sciences (physics, chemistry, biology, etc.)",
    "general machine learning (i.e., none of the above)"
]
