primary_areas = [
    "applications to neuroscience",
    "applications to physical sciences",
    "applications to robotics",
    "audio",
    "autonomy",
    "bayesian methods",
    "benchmarks",
    "biology",
    "causal reasoning",
    "chemistry",
    "cognitive science",
    "datasets",
    "fairness",
    "formal reasoning",
    "general machine learning",
    "generative models",
    "hardware",
    "hybrid ai systems",
    "infrastructure",
    "interpretation of learned representations",
    "kernel learning",
    "language",
    "learning on graphs",
    "learning theory",
    "lifelong learning",
    "logic",
    "meta learning",
    "metric learning",
    "neurosymbolic",
    "optimization",
    "other geometries",
    "other modalities",
    "physics",
    "physics-informed",
    "planning",
    "privacy",
    "probabilistic methods",
    "reinforcement learning",
    "representation learning for computer vision",
    "safety",
    "sampling",
    "self-supervised",
    "semi-supervised",
    "societal considerations",
    "software libraries",
    "sparse coding",
    "supervised representation learning",
    "topologies",
    "transfer learning",
    "unsupervised",
    "uq",
    "variational inference",
    "visualization",
]
