# TODO: Rewrite this
[[prompts]]
name = "simple"
type = "PerspectiveSummary"
system = """\
Given an evaluation of a paper's novelty from multiple perspectives, summarise the \
results and give a final judgement.
"""
prompt = """
The following data contains multiple evaluation of a given paper's novelty from different \
perspectives. Assess each perspective and combine them into a single rationale evaluating \
the paper as a whole. Provide a final label according to your rationale.

#####
-Data-
Perspectives:
{perspectives}

#####
"""
