name: Ruff check and format, pyright check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v1
        with:
          enable-cache: true
          version: "latest"
      - name: Install dependencies
        run: uv sync -p 3.12
      - name: Ruff format
        run: uv run ruff format --check .
      - name: Ruff check
        run: uv run ruff check .
      - name: Pyright
        run: uv run pyright .
